### ISSUE TITLE
Requiring app.js does not export nmr

### ISSUE THREAD

**Issue by Gum-Joe** [jakhu/no-more-rails#4]
When you require app.js, you may find you receive something similar to the following error:
```
TypeError: app.add is not a function
    at Object.<anonymous> (C:\Users\Kishan Sambhi\Documents\Projects\no-more-rails\test.js:2:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```
This is because app.js does not appear to export nmr (`lib/nmr.js`).
**Fix: require `lib/nmr.js` - `require('nmr/lib/nmr.js')`**
We will update `package.json` to set `lib/nmr.js` as the entry script.

**Comment by Gum-Joe** [comment]
Temporary fix created by @Gum-Joe in pull request #5 
Commit message:
Title: `Merge pull request #5 from Gum-Joe/master`
Message:
```
Modify package.json
# INFO
# Fix author: Gum-Joe
# Message from author:
## "I've created a temporary fix for #4 by making lib/nmr.js the main script
## Also, npm start will now run test.js"
# Files changed:
## package.json
# Merged at 16:56 on the 17/02/16
```
